import Head from "next/head";
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from "../components/Widgets";
import CommentModal from "../components/CommentModal";


export default function Home({newsResults, randomUserResults}) {
  return (
    <div >
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className='flex min-h-screen mx-auto '>  
      {/* Sidebar */}
      <Sidebar />

      {/* Feed */}
      <Feed/>
      {/* Widgets */}
      <Widgets
          newsResults={newsResults?.articles}
          randomUsersResults={randomUserResults?.results || null}
        />
      {/* Modal */}
      <CommentModal/>

    </main>


    </div>
  );
}

//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps(){
  let randomUsersResults = [];

  try {
    const res = await fetch(
      "https://randomuser.me/api/?results=30&inc=name,login,picture"
    );

    randomUsersResults = await res.json();
  } catch (e) {
    randomUsersResults = [];
  }

  // const randomUsersResults = await fetch(
  //   "https://randomuser.me/api/?results=30&inc=name,login,picture"
  // ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUserResults,
    },
  };
}