import Head from "next/head";
import Sidebar from '../../components/Sidebar';
import Widgets from "../../components/Widgets";
import CommentModal from "../../components/CommentModal";
import { SparklesIcon } from "@heroicons/react/outline";
import Input from "../../components/Input";
import { AnimatePresence } from "framer-motion";



export default function Post({newsResults, randomUserResults}) {
  return (
    <div >
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className='flex min-h-screen mx-auto '>  
      {/* Sidebar */}
      <Sidebar />

      {/* Feed */}

      <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl"> 
       {/* div is covering the header section taht has an edge to tag  */}
        <div className='flex py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200'>
              <h2 className="text-lg sm:text-xl font-bold cursor-pointer">Home</h2>
              <div className='hoverEffect flex items-center justify-center px-0 ml-auto w-9 h-9'>
                    <SparklesIcon className='h-5'/>
              </div>  
        </div> 
        <Input/>

        <AnimatePresence>
        {posts.map((post) => (
          <motion.div key={post.id} 
          initial={{opacity: 0}} 
          animate={{opacity: 1}} 
          exit={{opacity: 0}}
          transition={{duration: 1}}
          >
            <Post key={post.id} post={post}/>
          </motion.div>
        ))}

        </AnimatePresence>

    </div>

      {/* Widgets */}
      <Widgets newsResults={newsResults.articles}  randomUserResults={randomUserResults.results}/>
      {/* Modal */}
      <CommentModal/>

    </main>


    </div>
  );
}

//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps(){
  const newsResults = await fetch (
    "https://saurav.tech/NewsAPI/top-headlines/category/science/us.json"
    ).then((res) => res.json());

    //Who to follow section

    const randomUserResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture"
    ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUserResults,
    },
  };
}