import Head from "next/head";
import Sidebar from '../../components/Sidebar';
import Widgets from "../../components/Widgets";
import CommentModal from "../../components/CommentModal";
import { ArrowLeftIcon } from "@heroicons/react/solid";
import { useRouter } from "next/router";
import { Post } from "../../components/Post";




export default function Post({newsResults, randomUserResults}) {
  const router = useRouter()
    return (
    <div >
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className='flex min-h-screen mx-auto '>  
      {/* Sidebar */}
      <Sidebar />

      {/* Feed */}

      <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl"> 
       {/* div is covering the header section taht has an edge to tag  */}
        <div className='flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200'>
              <div className="hoverEffect" onClick={() => router.push("/")}>
                    <ArrowLeftIcon className="h-5"/>
              </div>
              <h2 className="text-lg sm:text-xl font-bold cursor-pointer">Tweet</h2>
        </div> 
        <Post/>
    </div>

      {/* Widgets */}
      <Widgets newsResults={newsResults.articles}  randomUserResults={randomUserResults.results}/>
      {/* Modal */}
      <CommentModal/>

    </main>


    </div>
  );
}

//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps(){
  const newsResults = await fetch (
    "https://saurav.tech/NewsAPI/top-headlines/category/science/us.json"
    ).then((res) => res.json());

    //Who to follow section

    const randomUserResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture"
    ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUserResults,
    },
  };
}