import Head from "next/head";
import Sidebar from '../../components/Sidebar';
import Widgets from "../../components/Widgets";
import CommentModal from "../../components/CommentModal";


export default function Post({newsResults, randomUserResults}) {
  return (
    <div >
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className='flex min-h-screen mx-auto '>  
      {/* Sidebar */}
      <Sidebar />


      {/* Widgets */}
      <Widgets newsResults={newsResults.articles}  randomUserResults={randomUserResults.results}/>
      {/* Modal */}
      <CommentModal/>

    </main>


    </div>
  );
}

//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps(){
  const newsResults = await fetch (
    "https://saurav.tech/NewsAPI/top-headlines/category/science/us.json"
    ).then((res) => res.json());

    //Who to follow section

    const randomUserResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture"
    ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUserResults,
    },
  };
}